import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("real files can be cleaned while YouTube history survives project deletion and reload", async ({ page, request }) => {
  await page.goto("/");
  await page.locator(".local-storage summary").click();
  await page.getByRole("button", { name: "管理影片檔案", exact: true }).click();
  const manager = page.getByRole("dialog", { name: "管理影片檔案", exact: true });
  await expect(manager.getByRole("button", { name: "刪除檔案：downloads/qa-original.mp4", exact: true })).toBeDisabled();
  await expect(manager.getByRole("checkbox", { name: "選取檔案：downloads/qa-original.mp4", exact: true })).toBeDisabled();
  const selectAll = manager.getByRole("checkbox", { name: "全選目前可刪檔案", exact: true });
  const chooseA = manager.getByRole("checkbox", { name: "選取檔案：downloads/qa-orphan-a.mp4", exact: true });
  await chooseA.check();
  expect(await selectAll.evaluate((element: HTMLInputElement) => element.indeterminate)).toBe(true);
  await manager.getByLabel("搜尋檔名或路徑").fill("qa-orphan-b");
  await expect(manager.getByRole("group", { name: "批次選取影片" })).toContainText("其中 1 個不在目前清單");
  await selectAll.check();
  await manager.getByLabel("搜尋檔名或路徑").fill("");
  await expect(selectAll).toBeChecked();
  await manager.getByLabel("檔案類型").selectOption("previews");
  await expect(manager.getByRole("group", { name: "批次選取影片" })).toContainText("其中 2 個不在目前清單");
  await manager.getByLabel("檔案類型").selectOption("sources");
  await manager.getByRole("button", { name: "刪除已選（2）", exact: true }).click();
  const batchConfirm = page.getByRole("alertdialog", { name: "永久刪除 2 個影片檔案？", exact: true });
  await expect(batchConfirm.getByRole("button", { name: "取消", exact: true })).toBeFocused();
  await expect(batchConfirm.getByRole("list", { name: "即將刪除的檔案" }).getByRole("listitem")).toHaveCount(2);
  await page.keyboard.press("Escape");
  await expect(chooseA).toBeChecked();
  await expect(manager.getByRole("button", { name: "刪除已選（2）", exact: true })).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await manager.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).include(".media-manager").analyze()).violations).toEqual([]);
  await page.screenshot({ path: "../runs/storage-history-qa/bulk-selection-mobile.png" });
  await page.setViewportSize({ width: 1440, height: 1080 });
  // Exercise partial success in the UI while the successful file is really
  // removed by the isolated backend. The failed file remains for a real retry.
  await page.route("**/api/storage/delete-batch", async route => {
    const { ids } = route.request().postDataJSON();
    const response = await route.fetch({ postData: JSON.stringify({ ids: [ids[0]] }) });
    const result = await response.json();
    await route.fulfill({ json: { ...result, failed: [{ id: ids[1], detail: "測試：檔案暫時無法刪除" }] } });
  }, { times: 1 });
  await manager.getByRole("button", { name: "刪除已選（2）", exact: true }).click();
  await batchConfirm.getByRole("button", { name: "永久刪除檔案", exact: true }).click();
  await expect(manager).toContainText("已刪除檔案：1 個");
  await expect(manager.getByRole("alert")).toContainText("1 個檔案未完成刪除");
  await expect(manager.getByRole("alert")).toContainText("測試：檔案暫時無法刪除");
  await manager.getByRole("button", { name: "刪除已選（1）", exact: true }).click();
  await page.getByRole("alertdialog").getByRole("button", { name: "永久刪除檔案", exact: true }).click();
  await expect(manager.getByRole("alert")).toHaveCount(0);
  await expect(manager.getByRole("button", { name: "刪除已選（0）", exact: true })).toBeDisabled();
  await manager.getByLabel("檔案類型").selectOption("exports");
  const removeClip = manager.getByRole("button", { name: "刪除檔案：clips/web/qa/qa-clip.mp4", exact: true });
  await removeClip.click();
  const confirm = page.getByRole("alertdialog", { name: "永久刪除這個影片檔案？", exact: true });
  await expect(confirm.getByRole("button", { name: "取消", exact: true })).toBeFocused();
  expect((await new AxeBuilder({ page }).include("[role=alertdialog]").analyze()).violations).toEqual([]);
  await page.keyboard.press("Escape");
  await expect(removeClip).toBeFocused();
  expect((await (await request.get("/api/state")).json()).jobs).toHaveLength(1);
  await removeClip.click();
  await confirm.getByRole("button", { name: "永久刪除檔案", exact: true }).click();
  await expect(manager).toContainText("已刪除檔案");
  expect((await (await request.get("/api/state")).json()).projects).toHaveLength(1);
  expect((await (await request.get("/api/state")).json()).jobs).toHaveLength(0);
  await manager.getByRole("button", { name: "關閉檔案管理" }).click();
  await page.getByRole("button", { name: "清理測試直播 的專案選單", exact: true }).click();
  await page.getByRole("menuitem", { name: "刪除專案…", exact: true }).click();
  const projectConfirm = page.getByRole("alertdialog", { name: "刪除專案？", exact: true });
  await expect(projectConfirm).toContainText("YouTube 匯入歷史會保留");
  await projectConfirm.getByRole("button", { name: "刪除專案", exact: true }).click();
  await expect(projectConfirm).toHaveCount(0);
  await page.getByRole("button", { name: "管理影片檔案", exact: true }).click();
  for (const [category, path] of [["sources", "downloads/qa-original.mp4"], ["previews", "runs/web/old/preview.mp4"]]) {
    await manager.getByLabel("檔案類型").selectOption(category);
    await manager.getByRole("checkbox", { name: `選取檔案：${path}`, exact: true }).check();
  }
  await manager.getByRole("button", { name: "刪除已選（2）", exact: true }).click();
  await batchConfirm.getByRole("button", { name: "永久刪除檔案", exact: true }).click();
  await expect(batchConfirm).toHaveCount(0);
  await expect(manager).toContainText("已刪除檔案：2 個");
  expect((await (await request.get("/api/storage")).json()).bytes).toBe(0);
  await manager.getByRole("button", { name: "關閉檔案管理" }).click();
  await page.reload();
  await page.getByRole("button", { name: "我的 YouTube", exact: true }).click();
  await page.getByRole("button", { name: "YouTube 匯入歷史", exact: true }).click();
  const history = page.getByRole("dialog", { name: "YouTube 匯入歷史", exact: true });
  await expect(history).toContainText("清理測試直播");
  await expect(history).toContainText("曾匯入完成 · 專案已刪除 · 1 次");
  await history.getByLabel("只看專案已刪除").check();
  await history.getByLabel("搜尋影片名稱或 ID").fill("abcdefghijk");
  await expect(history.getByRole("link")).toHaveCount(1);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await history.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).include(".media-manager").analyze()).violations).toEqual([]);
  await page.screenshot({ path: "../runs/storage-history-qa/history-mobile-tested.png" });
  await page.keyboard.press("Escape");
  await expect(history).toHaveCount(0);
  await expect(page.getByRole("dialog", { name: "我的 YouTube", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "YouTube 匯入歷史", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.getByRole("button", { name: "匯入影片", exact: true }).click();
  await page.getByRole("button", { name: "YouTube 網址", exact: true }).click();
  await page.getByLabel("公開影片網址").fill("https://youtu.be/abcdefghijk");
  await expect(page.getByRole("status").filter({ hasText: "這支影片曾建立匯入" })).toContainText("專案已刪除，但匯入歷史仍保留");
  await page.getByLabel("公開影片網址").fill("https://www.youtube.com/live/abcdefghijk");
  await expect(page.getByRole("status").filter({ hasText: "這支影片曾建立匯入" })).toContainText("清理測試直播");
});
